import sharp from 'sharp'
import path from 'node:path'
import fs from 'node:fs/promises'
import { existsSync } from 'node:fs'
import pngToIco from 'png-to-ico'

export interface FaviconResult {
  sessionDir: string
  files: {
    name: string
    path: string
    size: number
  }[]
  manifestJson: string
}

const SIZES = [16, 32, 48, 64, 96, 128, 192, 256, 512]
const ICO_SIZES = [16, 32, 48, 64]
const APPLE_TOUCH = 180

export async function generateFavicon(inputPath: string, sessionDir: string): Promise<FaviconResult> {
  const outDir = path.join(sessionDir, 'output', 'favicon')
  await fs.mkdir(outDir, { recursive: true })

  const pngDir = path.join(outDir, 'pngs')
  await fs.mkdir(pngDir, { recursive: true })

  const files: FaviconResult['files'] = []

  for (const size of SIZES) {
    const name = size === 192 ? 'android-chrome-192x192.png'
      : size === 512 ? 'android-chrome-512x512.png'
      : `favicon-${size}x${size}.png`
    const outPath = path.join(pngDir, name)
    await sharp(inputPath)
      .resize(size, size, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
      .png()
      .toFile(outPath)
    const stat = await fs.stat(outPath)
    files.push({ name, path: outPath, size: stat.size })
  }

  const applePath = path.join(pngDir, 'apple-touch-icon.png')
  await sharp(inputPath)
    .resize(APPLE_TOUCH, APPLE_TOUCH, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toFile(applePath)
  const appleStat = await fs.stat(applePath)
  files.push({ name: 'apple-touch-icon.png', path: applePath, size: appleStat.size })

  const icoPngPaths = ICO_SIZES.map(s => {
    const p = path.join(pngDir, `favicon-${s}x${s}.png`)
    if (!existsSync(p)) return null
    return p
  }).filter(Boolean) as string[]

  const icoBuf = await pngToIco(icoPngPaths) as Buffer
  const icoPath = path.join(outDir, 'favicon.ico')
  await fs.writeFile(icoPath, icoBuf)
  const icoStat = await fs.stat(icoPath)
  files.push({ name: 'favicon.ico', path: icoPath, size: icoStat.size })

  const manifestJson = JSON.stringify({
    name: 'App',
    short_name: 'App',
    description: 'Generated by media-tool',
    start_url: '/',
    display: 'standalone',
    background_color: '#ffffff',
    theme_color: '#6366f1',
    icons: [
      { src: '/favicon-192x192.png', sizes: '192x192', type: 'image/png' },
      { src: '/favicon-512x512.png', sizes: '512x512', type: 'image/png' },
    ],
  }, null, 2)

  const manifestPath = path.join(outDir, 'manifest.json')
  await fs.writeFile(manifestPath, manifestJson)
  files.push({ name: 'manifest.json', path: manifestPath, size: manifestJson.length })

  return { sessionDir, files, manifestJson }
}
